###Views
GET http://localhost:5000/posts

### Get all posts
GET http://localhost:5000/api/posts

### Create post
POST http://localhost:5000/api/posts
Content-Type: application/json

{
    "title": "Paisaje",
    "content": "  Los paisajes pueden ser de gran belleza escénica y a menudo son fuente de inspiración para artistas, fotógrafos y amantes de la naturaleza. También pueden tener un valor cultural, histórico o ecológico significativo, y a menudo son considerados patrimonio de la humanidad.",
    "imgUrl": " https://img.freepik.com/fotos-premium/escalera-madera-al-amanecer-al-estilo-paisajes-tropicales_916626-8049.jpg"
}


### Update post
PUT http://localhost:5000/api/posts/1
Content-Type: application/json

{
    "title": "Titulo actualizado",
    "content": "Actualizamos contenido",
    "imgUrl": "https://google.com"
}


### Delete post
DELETE http://localhost:5000/api/posts/1